---
title: "기초통계"
subtitle: "통계에 대한 다양한 기본지식을 학습합니다."
author: "이광춘"
date: "2022년 12월 27일"
output:
  xaringan::moon_reader:
    css: 
      - [default]
      - css/koRea_nhsr.css
    lib_dir: libs
    seal: false
    nature:
      ratio: 16:9
      highlightStyle: github
      highlightLines: true
      countIncrementalSlides: false
    includes:
      after_body: [css/koRea-logo.html]
editor_options: 
  chunk_output_type: console
---

```{r setup, include = FALSE}
library(showtext)
library(tidyverse)
library(NHSRtheme)
library(xaringanExtra)

xaringanExtra::use_panelset()
xaringanExtra::use_share_again()

options(
  htmltools.dir.version = FALSE, 
  htmltools.preserve.raw = FALSE,
  tibble.width = 60, tibble.print_min = 6,
  crayon.enabled = TRUE
)

knitr::opts_chunk$set(echo = FALSE, message=FALSE, warning=FALSE,
                      comment="", digits = 3, tidy = FALSE, prompt = FALSE, fig.align = 'center',
                      fig.width = 7.252,
                      fig.height = 4,
                      dpi = 300)

# uncomment the following lines if you want to use the NHS-R theme colours by default
# scale_fill_continuous <- partial(scale_fill_nhs, discrete = FALSE)
# scale_fill_discrete <- partial(scale_fill_nhs, discrete = TRUE)
# scale_colour_continuous <- partial(scale_colour_nhs, discrete = FALSE)
# scale_colour_discrete <- partial(scale_colour_nhs, discrete = TRUE)

source("util.R")

```


class: title-slide, left, bottom

# `r rmarkdown::metadata$title`
----
## **`r rmarkdown::metadata$subtitle`**
### `r rmarkdown::metadata$author`
### `r rmarkdown::metadata$date`

 
---
class: inverse, middle
name: digital-ranking

# 강의 개요

----

.pull-left[

4차 산업혁명은 .warmyellow[**디지털 전환(Digital Transformation)**] 이라는 용어로 대체되고 있으며
전세계가 디지털 전환을 통해 새로운 도약을 준비하고 있다.

이를 위해서 디지털 전환을 떠받치고 있는 **데이터 과학**을 심도 깊이 다루기 전에 
그 기반기술을 차례차례 살펴보자.

데이터 과학을 구성하는 통계학과 기계학습이 큰 축으로 볼 수 있다.

]
 
.pull-right[   
.left[

1\. **[.warmyellow[통계학]](#digital-ranking)** <br><br>
&nbsp;&nbsp;&nbsp;&nbsp;    1\.1\. 중심극한정리 <br>


2\. [마무리](#goodbye) 
]
] <!--end of right-column-->




<!---------------------- 1. 중심극한정리(정규분포) ------------------------------------->

```{r child='slideshows/statistics/clt_normal.Rmd'}
```


<!-- -------------------- 99. 마무리 ----------------------------- -->

```{r child='slideshows/statistics/goodbye.Rmd'}
```



