---
layout: page
title: "통계와 확률"
date: "2022-12-28"
output: 
  html_document: 
    toc: yes
    toc_depth: 2
    toc_float: true
    highlight: tango
    code_folding: hide
    number_section: true
    self_contained: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, message=FALSE, warning=FALSE,
                      comment="", digits = 3, tidy = FALSE, prompt = FALSE, fig.align = 'center')
```

# 정규분포

```{r}
slide_path <- glue::glue("{here::here()}/statistics.html")

xaringanExtra::embed_xaringan(
  url = slide_path,
  ratio = "16:9"
)
```

[바로가기](../../statistics.html)

## 중심극한정리

```{r}
slide_path <- glue::glue("{here::here()}/slideshows/statistics/distribution_clt.html")

xaringanExtra::embed_xaringan(
  url = slide_path,
  ratio = "16:9"
)
```

[바로가기](distribution_clt.html)


# 시각화

```{r}
library(tidyverse)

slide_path <- glue::glue("{here::here()}/slideshows/statistics/why_viz.html")

xaringanExtra::embed_xaringan(
  url = slide_path,
  ratio = "16:9"
)
```

[바로가기](why_viz.html)


# 가설 검정

```{r}

slide_path <- glue::glue("{here::here()}/slideshows/statistics/testing.html")

xaringanExtra::embed_xaringan(
  url = slide_path,
  ratio = "16:9"
)
```

[바로가기](testing.html)


# 단순 선형회귀

```{r}

slide_path <- glue::glue("{here::here()}/slideshows/statistics/ols.html")

xaringanExtra::embed_xaringan(
  url = slide_path,
  ratio = "16:9"
)
```

[바로가기](ols.html)


- 코드출처: [Gina Reynolds](https://evangelinereynolds.netlify.app/)


