---
title: "Test"
subtitle: "With flipbookr and xaringan"
author: "You!"
output:
  xaringan::moon_reader:
    lib_dir: libs
    css: [default, hygge, ninjutsu]
    nature:
      ratio: 16:9
      highlightStyle: github
      highlightLines: true
      countIncrementalSlides: false
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = F, 
                      warning = F, comment = "",
                      fig.height = 4, cache = T)
library(tidyverse)
library(flipbookr)
options(knitr.duplicate.label = "allow")
xaringanExtra::use_share_again()
xaringanExtra::use_panelset()
```


---
name: datasauRus

`r flipbookr::chunk_reveal("datasauRus", title = "### 공룡 데이터",  widths = c(50, 50))`


```{r datasauRus, include = FALSE, cache=TRUE}
library(tidyverse)

datasauRus::datasaurus_dozen %>%
  ggplot(aes(x = x,  y = y)) +
    geom_point() +
    facet_wrap(facets = vars(dataset)) +
    # mean of x
    ggxmean::geom_x_mean() +
    ggxmean::geom_y_mean() +
    # mean of y
    ggxmean:::geom_x1sd(linetype = "dashed") +
    ggxmean:::geom_y1sd(linetype = "dashed") +
    # linear model
    ggxmean::geom_lm() +
    ggxmean::geom_lm_formula() +
    # Pearson correlation
    ggxmean:::geom_corrlabel()
```


---
name: datasauRus-stat


.panelset[

.panel[.panel-name[평균]

.pull-left[

```{r datasauRus-mean, eval = FALSE, cache=TRUE, paged.print=FALSE}
datasauRus::datasaurus_dozen %>%
  pivot_longer(cols = x:y) %>% 
  group_by(dataset, name) %>% 
  summarise(mean  = mean(value)) %>% 
  pivot_wider(names_from = name, values_from = mean)
```
]
.pull-right[
```{r datasauRus-mean-out, ref.label="datasauRus-mean", echo=FALSE}
```
]
]

.panel[.panel-name[분산]

.pull-left[

```{r datasauRus-var, eval = FALSE, cache=TRUE, paged.print=FALSE}
datasauRus::datasaurus_dozen %>%
  pivot_longer(cols = x:y) %>% 
  group_by(dataset, name) %>% 
  summarise(var  = var(value)) %>% 
  pivot_wider(names_from = name, values_from = var)

```
]
.pull-right[
```{r datasauRus-var-out, ref.label="datasauRus-var", echo=FALSE}
```
]
]

.panel[.panel-name[상관계수]

.pull-left[

```{r datasauRus-cor, eval = FALSE, cache=TRUE, paged.print=FALSE}
custom_correlation <- function(df) {
  cor(df$x, df$y)
}

datasauRus::datasaurus_dozen %>%
  group_by(dataset) %>% 
  nest() %>% 
  mutate(corr = map(data, custom_correlation)) %>% 
  unnest(corr)

```
]
.pull-right[
```{r datasauRus-cor-out, ref.label="datasauRus-cor", echo=FALSE}
```
]
]

]



